# Generated by Django 5.2.7 on 2025-11-13 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'MARCA',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-13 18:40:00'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='app.marca'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id_resenia', models.AutoField(primary_key=True, serialize=False)),
                ('estrellas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_resenia', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='app.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='app.usuario')),
            ],
            options={
                'verbose_name_plural': 'resenias',
                'db_table': 'RESENIA',
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
