# Generated by Django 5.2.8 on 2025-11-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marca_producto_fecha_alta_alter_usuario_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo_url',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(blank=True),
        ),
    ]
